version: '3.8'
# This does not work yet. Just testing stuff out
services:
  flask:
    build: .
    container_name: flask_app
    ports:
      - "8001:8001"
    depends_on:
      - ollama
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    networks:
      - my_network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
