name: Deploy to Self-Hosted Server

on:
    push:
        branches: ["dev", "Github-Actions"]

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Stop Flask Server
              run: |
                fuser -k 8001/tcp || true

            - name: Build and Deploy
              run: |
                cd ~/Projects/project-copilot-clone-2/webserver
                source .venv/bin/activate
                pip install -r requirements.txt
  
            - name: Start Flask in tmux Session
              run: |
                tmux new-session -d -s flask_server 'bash -c "cd ~/Projects/project-copilot-clone-2/webserver && source .venv/bin/activate && sleep 5 && python app.py > flask.log 2>&1"'
                tmux ls || echo "No tmux sessions found"