# workflow for generating documentation

name: Documentation

on:
  push:
    branches: [ "main", "dev", "Github-Actions" ]

jobs:
  python-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      
  extension-docs:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v4

