# workflow for running tests

name: Tests

on:
  push:
    branches: [ "main", "dev", "Github-Actions" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
